### ISSUE TITLE
Error at osu_to_sqlite.py

### ISSUE THREAD

**Issue by timelessnesses** [jaasonw/osu-db-tools#3]
```bash
Traceback (most recent call last):
  File "C:\Users\Python Mooping\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1917, in __call__
    return self.func(*args)
  File "C:\Users\Python Mooping\Desktop\Danser\Danserlauncher.py", line 87, in read
    beatmaps = database(pathosu.get() + "\\osu!.db")
  File "C:\Users\Python Mooping\Desktop\Danser\tools\osutosqllite.py", line 14, in create_db
    sql.execute("DROP TABLE maps")
sqlite3.OperationalError: no such table: maps
```
This error is weird

**Comment by jaasonw** [comment]
Hm, looks like it tried to drop a table that didn't exist, I think because I was testing this on an already existing table, I can go ahead and add a check for it but you should be able to just comment out that line

**Comment by jaasonw** [comment]
That commit should fix it
